/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.magista.domain.tables.pojos;


import com.rbkmoney.magista.domain.enums.InvoiceEventType;
import com.rbkmoney.magista.domain.enums.InvoiceStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceEvent implements Serializable {

    private static final long serialVersionUID = 1490355379;

    private Long             id;
    private Long             eventId;
    private LocalDateTime    eventCreatedAt;
    private InvoiceEventType eventType;
    private String           invoiceId;
    private InvoiceStatus    invoiceStatus;
    private String           invoiceStatusDetails;

    public InvoiceEvent() {}

    public InvoiceEvent(InvoiceEvent value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.eventCreatedAt = value.eventCreatedAt;
        this.eventType = value.eventType;
        this.invoiceId = value.invoiceId;
        this.invoiceStatus = value.invoiceStatus;
        this.invoiceStatusDetails = value.invoiceStatusDetails;
    }

    public InvoiceEvent(
        Long             id,
        Long             eventId,
        LocalDateTime    eventCreatedAt,
        InvoiceEventType eventType,
        String           invoiceId,
        InvoiceStatus    invoiceStatus,
        String           invoiceStatusDetails
    ) {
        this.id = id;
        this.eventId = eventId;
        this.eventCreatedAt = eventCreatedAt;
        this.eventType = eventType;
        this.invoiceId = invoiceId;
        this.invoiceStatus = invoiceStatus;
        this.invoiceStatusDetails = invoiceStatusDetails;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public LocalDateTime getEventCreatedAt() {
        return this.eventCreatedAt;
    }

    public void setEventCreatedAt(LocalDateTime eventCreatedAt) {
        this.eventCreatedAt = eventCreatedAt;
    }

    public InvoiceEventType getEventType() {
        return this.eventType;
    }

    public void setEventType(InvoiceEventType eventType) {
        this.eventType = eventType;
    }

    public String getInvoiceId() {
        return this.invoiceId;
    }

    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    public InvoiceStatus getInvoiceStatus() {
        return this.invoiceStatus;
    }

    public void setInvoiceStatus(InvoiceStatus invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    public String getInvoiceStatusDetails() {
        return this.invoiceStatusDetails;
    }

    public void setInvoiceStatusDetails(String invoiceStatusDetails) {
        this.invoiceStatusDetails = invoiceStatusDetails;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InvoiceEvent other = (InvoiceEvent) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!eventId.equals(other.eventId))
            return false;
        if (eventCreatedAt == null) {
            if (other.eventCreatedAt != null)
                return false;
        }
        else if (!eventCreatedAt.equals(other.eventCreatedAt))
            return false;
        if (eventType == null) {
            if (other.eventType != null)
                return false;
        }
        else if (!eventType.equals(other.eventType))
            return false;
        if (invoiceId == null) {
            if (other.invoiceId != null)
                return false;
        }
        else if (!invoiceId.equals(other.invoiceId))
            return false;
        if (invoiceStatus == null) {
            if (other.invoiceStatus != null)
                return false;
        }
        else if (!invoiceStatus.equals(other.invoiceStatus))
            return false;
        if (invoiceStatusDetails == null) {
            if (other.invoiceStatusDetails != null)
                return false;
        }
        else if (!invoiceStatusDetails.equals(other.invoiceStatusDetails))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.eventCreatedAt == null) ? 0 : this.eventCreatedAt.hashCode());
        result = prime * result + ((this.eventType == null) ? 0 : this.eventType.hashCode());
        result = prime * result + ((this.invoiceId == null) ? 0 : this.invoiceId.hashCode());
        result = prime * result + ((this.invoiceStatus == null) ? 0 : this.invoiceStatus.hashCode());
        result = prime * result + ((this.invoiceStatusDetails == null) ? 0 : this.invoiceStatusDetails.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InvoiceEvent (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(eventCreatedAt);
        sb.append(", ").append(eventType);
        sb.append(", ").append(invoiceId);
        sb.append(", ").append(invoiceStatus);
        sb.append(", ").append(invoiceStatusDetails);

        sb.append(")");
        return sb.toString();
    }
}
