/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.magista.domain.tables.pojos;


import com.rbkmoney.magista.domain.enums.FailureClass;
import com.rbkmoney.magista.domain.enums.InvoiceEventType;
import com.rbkmoney.magista.domain.enums.InvoicePaymentStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentEvent implements Serializable {

    private static final long serialVersionUID = -33850132;

    private Long                 id;
    private Long                 eventId;
    private LocalDateTime        eventCreatedAt;
    private InvoiceEventType     eventType;
    private String               invoiceId;
    private String               paymentId;
    private InvoicePaymentStatus paymentStatus;
    private FailureClass         paymentOperationFailureClass;
    private String               paymentExternalFailure;
    private String               paymentExternalFailureReason;
    private Long                 paymentFee;
    private Long                 paymentProviderFee;
    private Long                 paymentExternalFee;
    private Long                 paymentDomainRevision;

    public PaymentEvent() {}

    public PaymentEvent(PaymentEvent value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.eventCreatedAt = value.eventCreatedAt;
        this.eventType = value.eventType;
        this.invoiceId = value.invoiceId;
        this.paymentId = value.paymentId;
        this.paymentStatus = value.paymentStatus;
        this.paymentOperationFailureClass = value.paymentOperationFailureClass;
        this.paymentExternalFailure = value.paymentExternalFailure;
        this.paymentExternalFailureReason = value.paymentExternalFailureReason;
        this.paymentFee = value.paymentFee;
        this.paymentProviderFee = value.paymentProviderFee;
        this.paymentExternalFee = value.paymentExternalFee;
        this.paymentDomainRevision = value.paymentDomainRevision;
    }

    public PaymentEvent(
        Long                 id,
        Long                 eventId,
        LocalDateTime        eventCreatedAt,
        InvoiceEventType     eventType,
        String               invoiceId,
        String               paymentId,
        InvoicePaymentStatus paymentStatus,
        FailureClass         paymentOperationFailureClass,
        String               paymentExternalFailure,
        String               paymentExternalFailureReason,
        Long                 paymentFee,
        Long                 paymentProviderFee,
        Long                 paymentExternalFee,
        Long                 paymentDomainRevision
    ) {
        this.id = id;
        this.eventId = eventId;
        this.eventCreatedAt = eventCreatedAt;
        this.eventType = eventType;
        this.invoiceId = invoiceId;
        this.paymentId = paymentId;
        this.paymentStatus = paymentStatus;
        this.paymentOperationFailureClass = paymentOperationFailureClass;
        this.paymentExternalFailure = paymentExternalFailure;
        this.paymentExternalFailureReason = paymentExternalFailureReason;
        this.paymentFee = paymentFee;
        this.paymentProviderFee = paymentProviderFee;
        this.paymentExternalFee = paymentExternalFee;
        this.paymentDomainRevision = paymentDomainRevision;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public LocalDateTime getEventCreatedAt() {
        return this.eventCreatedAt;
    }

    public void setEventCreatedAt(LocalDateTime eventCreatedAt) {
        this.eventCreatedAt = eventCreatedAt;
    }

    public InvoiceEventType getEventType() {
        return this.eventType;
    }

    public void setEventType(InvoiceEventType eventType) {
        this.eventType = eventType;
    }

    public String getInvoiceId() {
        return this.invoiceId;
    }

    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    public String getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    public InvoicePaymentStatus getPaymentStatus() {
        return this.paymentStatus;
    }

    public void setPaymentStatus(InvoicePaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public FailureClass getPaymentOperationFailureClass() {
        return this.paymentOperationFailureClass;
    }

    public void setPaymentOperationFailureClass(FailureClass paymentOperationFailureClass) {
        this.paymentOperationFailureClass = paymentOperationFailureClass;
    }

    public String getPaymentExternalFailure() {
        return this.paymentExternalFailure;
    }

    public void setPaymentExternalFailure(String paymentExternalFailure) {
        this.paymentExternalFailure = paymentExternalFailure;
    }

    public String getPaymentExternalFailureReason() {
        return this.paymentExternalFailureReason;
    }

    public void setPaymentExternalFailureReason(String paymentExternalFailureReason) {
        this.paymentExternalFailureReason = paymentExternalFailureReason;
    }

    public Long getPaymentFee() {
        return this.paymentFee;
    }

    public void setPaymentFee(Long paymentFee) {
        this.paymentFee = paymentFee;
    }

    public Long getPaymentProviderFee() {
        return this.paymentProviderFee;
    }

    public void setPaymentProviderFee(Long paymentProviderFee) {
        this.paymentProviderFee = paymentProviderFee;
    }

    public Long getPaymentExternalFee() {
        return this.paymentExternalFee;
    }

    public void setPaymentExternalFee(Long paymentExternalFee) {
        this.paymentExternalFee = paymentExternalFee;
    }

    public Long getPaymentDomainRevision() {
        return this.paymentDomainRevision;
    }

    public void setPaymentDomainRevision(Long paymentDomainRevision) {
        this.paymentDomainRevision = paymentDomainRevision;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PaymentEvent other = (PaymentEvent) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!eventId.equals(other.eventId))
            return false;
        if (eventCreatedAt == null) {
            if (other.eventCreatedAt != null)
                return false;
        }
        else if (!eventCreatedAt.equals(other.eventCreatedAt))
            return false;
        if (eventType == null) {
            if (other.eventType != null)
                return false;
        }
        else if (!eventType.equals(other.eventType))
            return false;
        if (invoiceId == null) {
            if (other.invoiceId != null)
                return false;
        }
        else if (!invoiceId.equals(other.invoiceId))
            return false;
        if (paymentId == null) {
            if (other.paymentId != null)
                return false;
        }
        else if (!paymentId.equals(other.paymentId))
            return false;
        if (paymentStatus == null) {
            if (other.paymentStatus != null)
                return false;
        }
        else if (!paymentStatus.equals(other.paymentStatus))
            return false;
        if (paymentOperationFailureClass == null) {
            if (other.paymentOperationFailureClass != null)
                return false;
        }
        else if (!paymentOperationFailureClass.equals(other.paymentOperationFailureClass))
            return false;
        if (paymentExternalFailure == null) {
            if (other.paymentExternalFailure != null)
                return false;
        }
        else if (!paymentExternalFailure.equals(other.paymentExternalFailure))
            return false;
        if (paymentExternalFailureReason == null) {
            if (other.paymentExternalFailureReason != null)
                return false;
        }
        else if (!paymentExternalFailureReason.equals(other.paymentExternalFailureReason))
            return false;
        if (paymentFee == null) {
            if (other.paymentFee != null)
                return false;
        }
        else if (!paymentFee.equals(other.paymentFee))
            return false;
        if (paymentProviderFee == null) {
            if (other.paymentProviderFee != null)
                return false;
        }
        else if (!paymentProviderFee.equals(other.paymentProviderFee))
            return false;
        if (paymentExternalFee == null) {
            if (other.paymentExternalFee != null)
                return false;
        }
        else if (!paymentExternalFee.equals(other.paymentExternalFee))
            return false;
        if (paymentDomainRevision == null) {
            if (other.paymentDomainRevision != null)
                return false;
        }
        else if (!paymentDomainRevision.equals(other.paymentDomainRevision))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.eventCreatedAt == null) ? 0 : this.eventCreatedAt.hashCode());
        result = prime * result + ((this.eventType == null) ? 0 : this.eventType.hashCode());
        result = prime * result + ((this.invoiceId == null) ? 0 : this.invoiceId.hashCode());
        result = prime * result + ((this.paymentId == null) ? 0 : this.paymentId.hashCode());
        result = prime * result + ((this.paymentStatus == null) ? 0 : this.paymentStatus.hashCode());
        result = prime * result + ((this.paymentOperationFailureClass == null) ? 0 : this.paymentOperationFailureClass.hashCode());
        result = prime * result + ((this.paymentExternalFailure == null) ? 0 : this.paymentExternalFailure.hashCode());
        result = prime * result + ((this.paymentExternalFailureReason == null) ? 0 : this.paymentExternalFailureReason.hashCode());
        result = prime * result + ((this.paymentFee == null) ? 0 : this.paymentFee.hashCode());
        result = prime * result + ((this.paymentProviderFee == null) ? 0 : this.paymentProviderFee.hashCode());
        result = prime * result + ((this.paymentExternalFee == null) ? 0 : this.paymentExternalFee.hashCode());
        result = prime * result + ((this.paymentDomainRevision == null) ? 0 : this.paymentDomainRevision.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PaymentEvent (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(eventCreatedAt);
        sb.append(", ").append(eventType);
        sb.append(", ").append(invoiceId);
        sb.append(", ").append(paymentId);
        sb.append(", ").append(paymentStatus);
        sb.append(", ").append(paymentOperationFailureClass);
        sb.append(", ").append(paymentExternalFailure);
        sb.append(", ").append(paymentExternalFailureReason);
        sb.append(", ").append(paymentFee);
        sb.append(", ").append(paymentProviderFee);
        sb.append(", ").append(paymentExternalFee);
        sb.append(", ").append(paymentDomainRevision);

        sb.append(")");
        return sb.toString();
    }
}
