server:
  port: '@server.port@'

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: '@db.url@'
    username: '@db.user@'
    password: '@db.password@'
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
      data-source-properties:
        reWriteBatchedInserts: true
  application:
    name: '@project.name@'
  flyway:
    schemas: mst

# need to fix dbinit
db:
  skip:
    validation: true

payouter:
  pooling:
    url: http://payouter:8022/repo
    querySize: 100
    maxPoolSize: 1
    delay: 5000
  handler:
    queue:
      limit: 100
    threadPoolSize: 2
    timeout: 500

columbus:
  url: http://columbus:8022/repo

retry-policy:
  maxAttempts: -1

cache:
  invoiceData:
    size: 10000
  paymentData:
    size: 10000

info:
  damsel:
    version: '@damsel.version@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
service:
  partyManagement:
    url: http://hellgate:8022/v1/processing/partymgmt
    networkTimeout: 5000
kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: magista
  consumer:
    group-id: magista-group-1
    max-poll-interval-ms: 60000
    max-session-timeout-ms: 60000
    throttling-timeout-ms: 1000
  topics:
    invoicing:
      id: mg-invoice-100-2
      consume:
        enabled: false
        max-poll-records: 500
        concurrency: 1
    invoice-template:
      id: mg-events-invoice-template
      consume:
        enabled: false
        max-poll-records: 50
        concurrency: 1
    pm-events-payout:
      id: pm-events-payout
      consume:
        enabled: false
        max-poll-records: 50
        concurrency: 1
  ssl:
    enabled: false

token-gen:
  key: jXnZr4u7x!A%D*G-KaPvSgVkYp3s5v8t/B?E(H+MbQeThWmZq4t7w9z$C&F)J@Nc

testcontainers:
  postgresql:
    tag: '11.4'
  kafka:
    tag: '6.2.0'
