server:
  port: @server.port@

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
      data-source-properties:
        reWriteBatchedInserts: true
  application:
    name: @project.name@
    flyway:
      schemas: mst

# need to fix dbinit
db:
  skip:
    validation: true

payouter:
  pooling:
    url: http://payouter:8022/repo
    querySize: 100
    maxPoolSize: 1
    delay: 5000
  handler:
    queue:
      limit: 100
    threadPoolSize: 2
    timeout: 500

columbus:
  url: http://columbus:8022/repo

retry-policy:
  maxAttempts: -1

cache:
  invoiceData:
    size: 10000
  paymentData:
    size: 10000

info:
  damsel:
    version: @damsel.version@

management:
  metrics:
    export:
      statsd:
        flavor: etsy

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: magista
  invoice:
    topic: mg-invoice-100-2
  consumer:
    group-id: magista-group-1
    enable-auto-commit: false
    auto-offset-reset: earliest
    concurrency: 1
    max-poll-records: 500
  topics:
    invoicing: mg-invoice-100-2
  ssl:
    enabled: false

token-gen:
  key: jXnZr4u7x!A%D*G-KaPvSgVkYp3s5v8t/B?E(H+MbQeThWmZq4t7w9z$C&F)J@Nc
