ALTER TYPE mst.invoice_event_type ADD VALUE 'INVOICE_PAYMENT_CHARGEBACK_CREATED';

ALTER TYPE mst.invoice_event_type ADD VALUE 'INVOICE_PAYMENT_CHARGEBACK_STATUS_CHANGED';

ALTER TYPE mst.invoice_event_type ADD VALUE 'INVOICE_PAYMENT_CHARGEBACK_BODY_CHANGED';

ALTER TYPE mst.invoice_event_type ADD VALUE 'INVOICE_PAYMENT_CHARGEBACK_LEVY_CHANGED';

ALTER TYPE mst.invoice_event_type ADD VALUE 'INVOICE_PAYMENT_CHARGEBACK_STAGE_CHANGE';

ALTER TYPE mst.invoice_event_type ADD VALUE 'INVOICE_PAYMENT_CHARGEBACK_CASHFLOW_CHANGED';

ALTER TYPE mst.invoice_payment_status ADD VALUE 'charged_back'
