DROP INDEX IF EXISTS invoice_stat_party_id_party_shop_id_invoice_created_at_idx;

DROP INDEX IF EXISTS invoice_stat_party_id_party_shop_id_payment_created_at_idx;

DROP INDEX IF EXISTS event_invoice_ms_key;

DROP INDEX IF EXISTS invoice_stat_invoice_created_at_idx;

DROP INDEX IF EXISTS invoice_stat_payment_created_at_idx;

DROP TABLE IF EXISTS invoice_event_stat;

DROP TABLE IF EXISTS payout_event_stat;

DROP TYPE IF EXISTS INVOICE_EVENT_CATEGORY;

DROP TYPE IF EXISTS INVOICE_PAYMENT_STATUS;

DROP TYPE IF EXISTS INVOICE_STATUS;

DROP TYPE IF EXISTS ADJUSTMENT_STATUS;

DROP TYPE IF EXISTS INVOICE_EVENT_TYPE;

DROP TYPE IF EXISTS INVOICE_PAYMENT_REFUND_STATUS;

DROP TYPE IF EXISTS PAYOUT_EVENT_CATEGORY;

DROP TYPE IF EXISTS PAYOUT_EVENT_TYPE;

DROP TYPE IF EXISTS PAYOUT_STATUS;

DROP TYPE IF EXISTS PAYOUT_TYPE;

