DROP INDEX mst.invoice_stat_party_id_party_shop_id_payment_created_at_idx;
DROP INDEX mst.invoice_stat_party_id_party_shop_id_invoice_created_at_idx;

CREATE INDEX invoice_stat_party_id_party_shop_id_event_created_at_idx
  ON mst.invoice_event_stat USING BTREE (id, party_id, party_shop_id, event_created_at);
