DROP TABLE mst.invoice_event_stat;
DROP TYPE mst.ADJUSTMENT_STATUS;
DROP TYPE mst.INVOICE_EVENT_CATEGORY;
DROP TYPE mst.INVOICE_EVENT_TYPE;
DROP TYPE mst.INVOICE_PAYMENT_STATUS;
DROP TYPE mst.INVOICE_STATUS;