/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.magista.domain.tables.records;


import com.rbkmoney.magista.domain.enums.AdjustmentStatus;
import com.rbkmoney.magista.domain.enums.InvoiceEventType;
import com.rbkmoney.magista.domain.tables.Adjustment;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdjustmentRecord extends UpdatableRecordImpl<AdjustmentRecord> implements Record18<Long, Long, LocalDateTime, InvoiceEventType, String, String, String, String, String, String, AdjustmentStatus, LocalDateTime, LocalDateTime, String, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1963807846;

    /**
     * Setter for <code>mst.adjustment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.adjustment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.adjustment.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.adjustment.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mst.adjustment.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.adjustment.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>mst.adjustment.event_type</code>.
     */
    public void setEventType(InvoiceEventType value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.adjustment.event_type</code>.
     */
    public InvoiceEventType getEventType() {
        return (InvoiceEventType) get(3);
    }

    /**
     * Setter for <code>mst.adjustment.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.adjustment.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mst.adjustment.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.adjustment.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_id</code>.
     */
    public void setAdjustmentId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_id</code>.
     */
    public String getAdjustmentId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mst.adjustment.party_id</code>.
     */
    public void setPartyId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mst.adjustment.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mst.adjustment.party_shop_id</code>.
     */
    public void setPartyShopId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mst.adjustment.party_shop_id</code>.
     */
    public String getPartyShopId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mst.adjustment.party_contract_id</code>.
     */
    public void setPartyContractId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mst.adjustment.party_contract_id</code>.
     */
    public String getPartyContractId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_status</code>.
     */
    public void setAdjustmentStatus(AdjustmentStatus value) {
        set(10, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_status</code>.
     */
    public AdjustmentStatus getAdjustmentStatus() {
        return (AdjustmentStatus) get(10);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_status_created_at</code>.
     */
    public void setAdjustmentStatusCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_status_created_at</code>.
     */
    public LocalDateTime getAdjustmentStatusCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_created_at</code>.
     */
    public void setAdjustmentCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_created_at</code>.
     */
    public LocalDateTime getAdjustmentCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_reason</code>.
     */
    public void setAdjustmentReason(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_reason</code>.
     */
    public String getAdjustmentReason() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_fee</code>.
     */
    public void setAdjustmentFee(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_fee</code>.
     */
    public Long getAdjustmentFee() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_provider_fee</code>.
     */
    public void setAdjustmentProviderFee(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_provider_fee</code>.
     */
    public Long getAdjustmentProviderFee() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_external_fee</code>.
     */
    public void setAdjustmentExternalFee(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_external_fee</code>.
     */
    public Long getAdjustmentExternalFee() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>mst.adjustment.adjustment_domain_revision</code>.
     */
    public void setAdjustmentDomainRevision(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>mst.adjustment.adjustment_domain_revision</code>.
     */
    public Long getAdjustmentDomainRevision() {
        return (Long) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, LocalDateTime, InvoiceEventType, String, String, String, String, String, String, AdjustmentStatus, LocalDateTime, LocalDateTime, String, Long, Long, Long, Long> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, LocalDateTime, InvoiceEventType, String, String, String, String, String, String, AdjustmentStatus, LocalDateTime, LocalDateTime, String, Long, Long, Long, Long> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Adjustment.ADJUSTMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Adjustment.ADJUSTMENT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return Adjustment.ADJUSTMENT.EVENT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<InvoiceEventType> field4() {
        return Adjustment.ADJUSTMENT.EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Adjustment.ADJUSTMENT.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Adjustment.ADJUSTMENT.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Adjustment.ADJUSTMENT.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Adjustment.ADJUSTMENT.PARTY_SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Adjustment.ADJUSTMENT.PARTY_CONTRACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AdjustmentStatus> field11() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_STATUS_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_PROVIDER_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_EXTERNAL_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_DOMAIN_REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getEventCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceEventType value4() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAdjustmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPartyShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPartyContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentStatus value11() {
        return getAdjustmentStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getAdjustmentStatusCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getAdjustmentCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getAdjustmentReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getAdjustmentFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getAdjustmentProviderFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getAdjustmentExternalFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getAdjustmentDomainRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value3(LocalDateTime value) {
        setEventCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value4(InvoiceEventType value) {
        setEventType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value5(String value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value6(String value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value7(String value) {
        setAdjustmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value8(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value9(String value) {
        setPartyShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value10(String value) {
        setPartyContractId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value11(AdjustmentStatus value) {
        setAdjustmentStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value12(LocalDateTime value) {
        setAdjustmentStatusCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value13(LocalDateTime value) {
        setAdjustmentCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value14(String value) {
        setAdjustmentReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value15(Long value) {
        setAdjustmentFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value16(Long value) {
        setAdjustmentProviderFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value17(Long value) {
        setAdjustmentExternalFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value18(Long value) {
        setAdjustmentDomainRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord values(Long value1, Long value2, LocalDateTime value3, InvoiceEventType value4, String value5, String value6, String value7, String value8, String value9, String value10, AdjustmentStatus value11, LocalDateTime value12, LocalDateTime value13, String value14, Long value15, Long value16, Long value17, Long value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdjustmentRecord
     */
    public AdjustmentRecord() {
        super(Adjustment.ADJUSTMENT);
    }

    /**
     * Create a detached, initialised AdjustmentRecord
     */
    public AdjustmentRecord(Long id, Long eventId, LocalDateTime eventCreatedAt, InvoiceEventType eventType, String invoiceId, String paymentId, String adjustmentId, String partyId, String partyShopId, String partyContractId, AdjustmentStatus adjustmentStatus, LocalDateTime adjustmentStatusCreatedAt, LocalDateTime adjustmentCreatedAt, String adjustmentReason, Long adjustmentFee, Long adjustmentProviderFee, Long adjustmentExternalFee, Long adjustmentDomainRevision) {
        super(Adjustment.ADJUSTMENT);

        set(0, id);
        set(1, eventId);
        set(2, eventCreatedAt);
        set(3, eventType);
        set(4, invoiceId);
        set(5, paymentId);
        set(6, adjustmentId);
        set(7, partyId);
        set(8, partyShopId);
        set(9, partyContractId);
        set(10, adjustmentStatus);
        set(11, adjustmentStatusCreatedAt);
        set(12, adjustmentCreatedAt);
        set(13, adjustmentReason);
        set(14, adjustmentFee);
        set(15, adjustmentProviderFee);
        set(16, adjustmentExternalFee);
        set(17, adjustmentDomainRevision);
    }
}
