/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.magista.domain.tables.records;


import com.rbkmoney.magista.domain.enums.InvoiceEventCategory;
import com.rbkmoney.magista.domain.enums.InvoiceEventType;
import com.rbkmoney.magista.domain.enums.InvoicePaymentStatus;
import com.rbkmoney.magista.domain.enums.InvoiceStatus;
import com.rbkmoney.magista.domain.tables.InvoiceEventStat;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceEventStatRecord extends UpdatableRecordImpl<InvoiceEventStatRecord> {

    private static final long serialVersionUID = -1769071901;

    /**
     * Setter for <code>mst.invoice_event_stat.event_id</code>.
     */
    public void setEventId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.event_category</code>.
     */
    public void setEventCategory(InvoiceEventCategory value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.event_category</code>.
     */
    public InvoiceEventCategory getEventCategory() {
        return (InvoiceEventCategory) get(1);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.event_type</code>.
     */
    public void setEventType(InvoiceEventType value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.event_type</code>.
     */
    public InvoiceEventType getEventType() {
        return (InvoiceEventType) get(2);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_id</code>.
     */
    public void setPartyId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_email</code>.
     */
    public void setPartyEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_email</code>.
     */
    public String getPartyEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_shop_id</code>.
     */
    public void setPartyShopId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_shop_id</code>.
     */
    public Integer getPartyShopId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_shop_name</code>.
     */
    public void setPartyShopName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_shop_name</code>.
     */
    public String getPartyShopName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_shop_description</code>.
     */
    public void setPartyShopDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_shop_description</code>.
     */
    public String getPartyShopDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_shop_url</code>.
     */
    public void setPartyShopUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_shop_url</code>.
     */
    public String getPartyShopUrl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_shop_category_id</code>.
     */
    public void setPartyShopCategoryId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_shop_category_id</code>.
     */
    public Integer getPartyShopCategoryId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_shop_payout_tool_id</code>.
     */
    public void setPartyShopPayoutToolId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_shop_payout_tool_id</code>.
     */
    public Integer getPartyShopPayoutToolId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_contract_id</code>.
     */
    public void setPartyContractId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_contract_id</code>.
     */
    public Integer getPartyContractId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_contract_registered_number</code>.
     */
    public void setPartyContractRegisteredNumber(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_contract_registered_number</code>.
     */
    public String getPartyContractRegisteredNumber() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.party_contract_inn</code>.
     */
    public void setPartyContractInn(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.party_contract_inn</code>.
     */
    public String getPartyContractInn() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_status</code>.
     */
    public void setInvoiceStatus(InvoiceStatus value) {
        set(16, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_status</code>.
     */
    public InvoiceStatus getInvoiceStatus() {
        return (InvoiceStatus) get(16);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_status_details</code>.
     */
    public void setInvoiceStatusDetails(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_status_details</code>.
     */
    public String getInvoiceStatusDetails() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_product</code>.
     */
    public void setInvoiceProduct(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_product</code>.
     */
    public String getInvoiceProduct() {
        return (String) get(18);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_description</code>.
     */
    public void setInvoiceDescription(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_description</code>.
     */
    public String getInvoiceDescription() {
        return (String) get(19);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_amount</code>.
     */
    public void setInvoiceAmount(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_amount</code>.
     */
    public Long getInvoiceAmount() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_currency_code</code>.
     */
    public void setInvoiceCurrencyCode(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_currency_code</code>.
     */
    public String getInvoiceCurrencyCode() {
        return (String) get(21);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_due</code>.
     */
    public void setInvoiceDue(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_due</code>.
     */
    public LocalDateTime getInvoiceDue() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_created_at</code>.
     */
    public void setInvoiceCreatedAt(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_created_at</code>.
     */
    public LocalDateTime getInvoiceCreatedAt() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.invoice_context</code>.
     */
    public void setInvoiceContext(byte... value) {
        set(24, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.invoice_context</code>.
     */
    public byte[] getInvoiceContext() {
        return (byte[]) get(24);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(25);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_status</code>.
     */
    public void setPaymentStatus(InvoicePaymentStatus value) {
        set(26, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_status</code>.
     */
    public InvoicePaymentStatus getPaymentStatus() {
        return (InvoicePaymentStatus) get(26);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_status_failure_code</code>.
     */
    public void setPaymentStatusFailureCode(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_status_failure_code</code>.
     */
    public String getPaymentStatusFailureCode() {
        return (String) get(27);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_status_failure_description</code>.
     */
    public void setPaymentStatusFailureDescription(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_status_failure_description</code>.
     */
    public String getPaymentStatusFailureDescription() {
        return (String) get(28);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_amount</code>.
     */
    public void setPaymentAmount(Long value) {
        set(29, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_amount</code>.
     */
    public Long getPaymentAmount() {
        return (Long) get(29);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_currency_code</code>.
     */
    public void setPaymentCurrencyCode(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_currency_code</code>.
     */
    public String getPaymentCurrencyCode() {
        return (String) get(30);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_fee</code>.
     */
    public void setPaymentFee(Long value) {
        set(31, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_fee</code>.
     */
    public Long getPaymentFee() {
        return (Long) get(31);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_tool</code>.
     */
    public void setPaymentTool(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_tool</code>.
     */
    public String getPaymentTool() {
        return (String) get(32);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_masked_pan</code>.
     */
    public void setPaymentMaskedPan(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_masked_pan</code>.
     */
    public String getPaymentMaskedPan() {
        return (String) get(33);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_bin</code>.
     */
    public void setPaymentBin(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_bin</code>.
     */
    public String getPaymentBin() {
        return (String) get(34);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_token</code>.
     */
    public void setPaymentToken(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_token</code>.
     */
    public String getPaymentToken() {
        return (String) get(35);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_system</code>.
     */
    public void setPaymentSystem(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_system</code>.
     */
    public String getPaymentSystem() {
        return (String) get(36);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_session_id</code>.
     */
    public void setPaymentSessionId(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_session_id</code>.
     */
    public String getPaymentSessionId() {
        return (String) get(37);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_country_id</code>.
     */
    public void setPaymentCountryId(Integer value) {
        set(38, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_country_id</code>.
     */
    public Integer getPaymentCountryId() {
        return (Integer) get(38);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_city_id</code>.
     */
    public void setPaymentCityId(Integer value) {
        set(39, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_city_id</code>.
     */
    public Integer getPaymentCityId() {
        return (Integer) get(39);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_ip</code>.
     */
    public void setPaymentIp(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_ip</code>.
     */
    public String getPaymentIp() {
        return (String) get(40);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_phone_number</code>.
     */
    public void setPaymentPhoneNumber(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_phone_number</code>.
     */
    public String getPaymentPhoneNumber() {
        return (String) get(41);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_email</code>.
     */
    public void setPaymentEmail(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_email</code>.
     */
    public String getPaymentEmail() {
        return (String) get(42);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_fingerprint</code>.
     */
    public void setPaymentFingerprint(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_fingerprint</code>.
     */
    public String getPaymentFingerprint() {
        return (String) get(43);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_created_at</code>.
     */
    public void setPaymentCreatedAt(LocalDateTime value) {
        set(44, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_created_at</code>.
     */
    public LocalDateTime getPaymentCreatedAt() {
        return (LocalDateTime) get(44);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_context</code>.
     */
    public void setPaymentContext(byte... value) {
        set(45, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_context</code>.
     */
    public byte[] getPaymentContext() {
        return (byte[]) get(45);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_provider_fee</code>.
     */
    public void setPaymentProviderFee(Long value) {
        set(46, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_provider_fee</code>.
     */
    public Long getPaymentProviderFee() {
        return (Long) get(46);
    }

    /**
     * Setter for <code>mst.invoice_event_stat.payment_external_fee</code>.
     */
    public void setPaymentExternalFee(Long value) {
        set(47, value);
    }

    /**
     * Getter for <code>mst.invoice_event_stat.payment_external_fee</code>.
     */
    public Long getPaymentExternalFee() {
        return (Long) get(47);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceEventStatRecord
     */
    public InvoiceEventStatRecord() {
        super(InvoiceEventStat.INVOICE_EVENT_STAT);
    }

    /**
     * Create a detached, initialised InvoiceEventStatRecord
     */
    public InvoiceEventStatRecord(Long eventId, InvoiceEventCategory eventCategory, InvoiceEventType eventType, LocalDateTime eventCreatedAt, String partyId, String partyEmail, Integer partyShopId, String partyShopName, String partyShopDescription, String partyShopUrl, Integer partyShopCategoryId, Integer partyShopPayoutToolId, Integer partyContractId, String partyContractRegisteredNumber, String partyContractInn, String invoiceId, InvoiceStatus invoiceStatus, String invoiceStatusDetails, String invoiceProduct, String invoiceDescription, Long invoiceAmount, String invoiceCurrencyCode, LocalDateTime invoiceDue, LocalDateTime invoiceCreatedAt, byte[] invoiceContext, String paymentId, InvoicePaymentStatus paymentStatus, String paymentStatusFailureCode, String paymentStatusFailureDescription, Long paymentAmount, String paymentCurrencyCode, Long paymentFee, String paymentTool, String paymentMaskedPan, String paymentBin, String paymentToken, String paymentSystem, String paymentSessionId, Integer paymentCountryId, Integer paymentCityId, String paymentIp, String paymentPhoneNumber, String paymentEmail, String paymentFingerprint, LocalDateTime paymentCreatedAt, byte[] paymentContext, Long paymentProviderFee, Long paymentExternalFee) {
        super(InvoiceEventStat.INVOICE_EVENT_STAT);

        set(0, eventId);
        set(1, eventCategory);
        set(2, eventType);
        set(3, eventCreatedAt);
        set(4, partyId);
        set(5, partyEmail);
        set(6, partyShopId);
        set(7, partyShopName);
        set(8, partyShopDescription);
        set(9, partyShopUrl);
        set(10, partyShopCategoryId);
        set(11, partyShopPayoutToolId);
        set(12, partyContractId);
        set(13, partyContractRegisteredNumber);
        set(14, partyContractInn);
        set(15, invoiceId);
        set(16, invoiceStatus);
        set(17, invoiceStatusDetails);
        set(18, invoiceProduct);
        set(19, invoiceDescription);
        set(20, invoiceAmount);
        set(21, invoiceCurrencyCode);
        set(22, invoiceDue);
        set(23, invoiceCreatedAt);
        set(24, invoiceContext);
        set(25, paymentId);
        set(26, paymentStatus);
        set(27, paymentStatusFailureCode);
        set(28, paymentStatusFailureDescription);
        set(29, paymentAmount);
        set(30, paymentCurrencyCode);
        set(31, paymentFee);
        set(32, paymentTool);
        set(33, paymentMaskedPan);
        set(34, paymentBin);
        set(35, paymentToken);
        set(36, paymentSystem);
        set(37, paymentSessionId);
        set(38, paymentCountryId);
        set(39, paymentCityId);
        set(40, paymentIp);
        set(41, paymentPhoneNumber);
        set(42, paymentEmail);
        set(43, paymentFingerprint);
        set(44, paymentCreatedAt);
        set(45, paymentContext);
        set(46, paymentProviderFee);
        set(47, paymentExternalFee);
    }
}
