/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.magista.domain.tables.records;


import com.rbkmoney.magista.domain.tables.InvoiceData;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceDataRecord extends UpdatableRecordImpl<InvoiceDataRecord> implements Record16<Long, UUID, String, String, String, String, String, Long, String, LocalDateTime, LocalDateTime, Long, String, String, String, byte[]> {

    private static final long serialVersionUID = -1166158524;

    /**
     * Setter for <code>mst.invoice_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.invoice_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.invoice_data.party_id</code>.
     */
    public void setPartyId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.invoice_data.party_id</code>.
     */
    public UUID getPartyId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>mst.invoice_data.party_shop_id</code>.
     */
    public void setPartyShopId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.invoice_data.party_shop_id</code>.
     */
    public String getPartyShopId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mst.invoice_data.party_contract_id</code>.
     */
    public void setPartyContractId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.invoice_data.party_contract_id</code>.
     */
    public String getPartyContractId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_product</code>.
     */
    public void setInvoiceProduct(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_product</code>.
     */
    public String getInvoiceProduct() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_description</code>.
     */
    public void setInvoiceDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_description</code>.
     */
    public String getInvoiceDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_amount</code>.
     */
    public void setInvoiceAmount(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_amount</code>.
     */
    public Long getInvoiceAmount() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_currency_code</code>.
     */
    public void setInvoiceCurrencyCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_currency_code</code>.
     */
    public String getInvoiceCurrencyCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_due</code>.
     */
    public void setInvoiceDue(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_due</code>.
     */
    public LocalDateTime getInvoiceDue() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_created_at</code>.
     */
    public void setInvoiceCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_created_at</code>.
     */
    public LocalDateTime getInvoiceCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_party_revision</code>.
     */
    public void setInvoicePartyRevision(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_party_revision</code>.
     */
    public Long getInvoicePartyRevision() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_template_id</code>.
     */
    public void setInvoiceTemplateId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_template_id</code>.
     */
    public String getInvoiceTemplateId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_cart_json</code>.
     */
    public void setInvoiceCartJson(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_cart_json</code>.
     */
    public String getInvoiceCartJson() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_context_type</code>.
     */
    public void setInvoiceContextType(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_context_type</code>.
     */
    public String getInvoiceContextType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mst.invoice_data.invoice_context</code>.
     */
    public void setInvoiceContext(byte... value) {
        set(15, value);
    }

    /**
     * Getter for <code>mst.invoice_data.invoice_context</code>.
     */
    public byte[] getInvoiceContext() {
        return (byte[]) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, UUID, String, String, String, String, String, Long, String, LocalDateTime, LocalDateTime, Long, String, String, String, byte[]> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, UUID, String, String, String, String, String, Long, String, LocalDateTime, LocalDateTime, Long, String, String, String, byte[]> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return InvoiceData.INVOICE_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return InvoiceData.INVOICE_DATA.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return InvoiceData.INVOICE_DATA.PARTY_SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return InvoiceData.INVOICE_DATA.PARTY_CONTRACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return InvoiceData.INVOICE_DATA.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return InvoiceData.INVOICE_DATA.INVOICE_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return InvoiceData.INVOICE_DATA.INVOICE_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return InvoiceData.INVOICE_DATA.INVOICE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return InvoiceData.INVOICE_DATA.INVOICE_CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return InvoiceData.INVOICE_DATA.INVOICE_DUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return InvoiceData.INVOICE_DATA.INVOICE_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return InvoiceData.INVOICE_DATA.INVOICE_PARTY_REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return InvoiceData.INVOICE_DATA.INVOICE_TEMPLATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return InvoiceData.INVOICE_DATA.INVOICE_CART_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return InvoiceData.INVOICE_DATA.INVOICE_CONTEXT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field16() {
        return InvoiceData.INVOICE_DATA.INVOICE_CONTEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPartyShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPartyContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getInvoiceProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInvoiceDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getInvoiceAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getInvoiceCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getInvoiceDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getInvoiceCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getInvoicePartyRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getInvoiceTemplateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getInvoiceCartJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getInvoiceContextType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value16() {
        return getInvoiceContext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value2(UUID value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value3(String value) {
        setPartyShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value4(String value) {
        setPartyContractId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value5(String value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value6(String value) {
        setInvoiceProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value7(String value) {
        setInvoiceDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value8(Long value) {
        setInvoiceAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value9(String value) {
        setInvoiceCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value10(LocalDateTime value) {
        setInvoiceDue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value11(LocalDateTime value) {
        setInvoiceCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value12(Long value) {
        setInvoicePartyRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value13(String value) {
        setInvoiceTemplateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value14(String value) {
        setInvoiceCartJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value15(String value) {
        setInvoiceContextType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord value16(byte... value) {
        setInvoiceContext(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceDataRecord values(Long value1, UUID value2, String value3, String value4, String value5, String value6, String value7, Long value8, String value9, LocalDateTime value10, LocalDateTime value11, Long value12, String value13, String value14, String value15, byte[] value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceDataRecord
     */
    public InvoiceDataRecord() {
        super(InvoiceData.INVOICE_DATA);
    }

    /**
     * Create a detached, initialised InvoiceDataRecord
     */
    public InvoiceDataRecord(Long id, UUID partyId, String partyShopId, String partyContractId, String invoiceId, String invoiceProduct, String invoiceDescription, Long invoiceAmount, String invoiceCurrencyCode, LocalDateTime invoiceDue, LocalDateTime invoiceCreatedAt, Long invoicePartyRevision, String invoiceTemplateId, String invoiceCartJson, String invoiceContextType, byte[] invoiceContext) {
        super(InvoiceData.INVOICE_DATA);

        set(0, id);
        set(1, partyId);
        set(2, partyShopId);
        set(3, partyContractId);
        set(4, invoiceId);
        set(5, invoiceProduct);
        set(6, invoiceDescription);
        set(7, invoiceAmount);
        set(8, invoiceCurrencyCode);
        set(9, invoiceDue);
        set(10, invoiceCreatedAt);
        set(11, invoicePartyRevision);
        set(12, invoiceTemplateId);
        set(13, invoiceCartJson);
        set(14, invoiceContextType);
        set(15, invoiceContext);
    }
}
