/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.magista.domain.tables.records;


import com.rbkmoney.magista.domain.enums.FailureClass;
import com.rbkmoney.magista.domain.enums.InvoiceEventType;
import com.rbkmoney.magista.domain.enums.InvoicePaymentStatus;
import com.rbkmoney.magista.domain.tables.PaymentEvent;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentEventRecord extends UpdatableRecordImpl<PaymentEventRecord> implements Record14<Long, Long, LocalDateTime, InvoiceEventType, String, String, InvoicePaymentStatus, FailureClass, String, String, Long, Long, Long, Long> {

    private static final long serialVersionUID = -1999691507;

    /**
     * Setter for <code>mst.payment_event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.payment_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.payment_event.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.payment_event.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mst.payment_event.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.payment_event.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>mst.payment_event.event_type</code>.
     */
    public void setEventType(InvoiceEventType value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.payment_event.event_type</code>.
     */
    public InvoiceEventType getEventType() {
        return (InvoiceEventType) get(3);
    }

    /**
     * Setter for <code>mst.payment_event.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.payment_event.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mst.payment_event.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mst.payment_event.payment_status</code>.
     */
    public void setPaymentStatus(InvoicePaymentStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_status</code>.
     */
    public InvoicePaymentStatus getPaymentStatus() {
        return (InvoicePaymentStatus) get(6);
    }

    /**
     * Setter for <code>mst.payment_event.payment_operation_failure_class</code>.
     */
    public void setPaymentOperationFailureClass(FailureClass value) {
        set(7, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_operation_failure_class</code>.
     */
    public FailureClass getPaymentOperationFailureClass() {
        return (FailureClass) get(7);
    }

    /**
     * Setter for <code>mst.payment_event.payment_external_failure</code>.
     */
    public void setPaymentExternalFailure(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_external_failure</code>.
     */
    public String getPaymentExternalFailure() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mst.payment_event.payment_external_failure_reason</code>.
     */
    public void setPaymentExternalFailureReason(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_external_failure_reason</code>.
     */
    public String getPaymentExternalFailureReason() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mst.payment_event.payment_fee</code>.
     */
    public void setPaymentFee(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_fee</code>.
     */
    public Long getPaymentFee() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>mst.payment_event.payment_provider_fee</code>.
     */
    public void setPaymentProviderFee(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_provider_fee</code>.
     */
    public Long getPaymentProviderFee() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>mst.payment_event.payment_external_fee</code>.
     */
    public void setPaymentExternalFee(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_external_fee</code>.
     */
    public Long getPaymentExternalFee() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>mst.payment_event.payment_domain_revision</code>.
     */
    public void setPaymentDomainRevision(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>mst.payment_event.payment_domain_revision</code>.
     */
    public Long getPaymentDomainRevision() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, LocalDateTime, InvoiceEventType, String, String, InvoicePaymentStatus, FailureClass, String, String, Long, Long, Long, Long> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, LocalDateTime, InvoiceEventType, String, String, InvoicePaymentStatus, FailureClass, String, String, Long, Long, Long, Long> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PaymentEvent.PAYMENT_EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PaymentEvent.PAYMENT_EVENT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return PaymentEvent.PAYMENT_EVENT.EVENT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<InvoiceEventType> field4() {
        return PaymentEvent.PAYMENT_EVENT.EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PaymentEvent.PAYMENT_EVENT.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<InvoicePaymentStatus> field7() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<FailureClass> field8() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_OPERATION_FAILURE_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_EXTERNAL_FAILURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_EXTERNAL_FAILURE_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_PROVIDER_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_EXTERNAL_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return PaymentEvent.PAYMENT_EVENT.PAYMENT_DOMAIN_REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getEventCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceEventType value4() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicePaymentStatus value7() {
        return getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FailureClass value8() {
        return getPaymentOperationFailureClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPaymentExternalFailure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPaymentExternalFailureReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getPaymentFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getPaymentProviderFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getPaymentExternalFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getPaymentDomainRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value3(LocalDateTime value) {
        setEventCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value4(InvoiceEventType value) {
        setEventType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value5(String value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value6(String value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value7(InvoicePaymentStatus value) {
        setPaymentStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value8(FailureClass value) {
        setPaymentOperationFailureClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value9(String value) {
        setPaymentExternalFailure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value10(String value) {
        setPaymentExternalFailureReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value11(Long value) {
        setPaymentFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value12(Long value) {
        setPaymentProviderFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value13(Long value) {
        setPaymentExternalFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord value14(Long value) {
        setPaymentDomainRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentEventRecord values(Long value1, Long value2, LocalDateTime value3, InvoiceEventType value4, String value5, String value6, InvoicePaymentStatus value7, FailureClass value8, String value9, String value10, Long value11, Long value12, Long value13, Long value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentEventRecord
     */
    public PaymentEventRecord() {
        super(PaymentEvent.PAYMENT_EVENT);
    }

    /**
     * Create a detached, initialised PaymentEventRecord
     */
    public PaymentEventRecord(Long id, Long eventId, LocalDateTime eventCreatedAt, InvoiceEventType eventType, String invoiceId, String paymentId, InvoicePaymentStatus paymentStatus, FailureClass paymentOperationFailureClass, String paymentExternalFailure, String paymentExternalFailureReason, Long paymentFee, Long paymentProviderFee, Long paymentExternalFee, Long paymentDomainRevision) {
        super(PaymentEvent.PAYMENT_EVENT);

        set(0, id);
        set(1, eventId);
        set(2, eventCreatedAt);
        set(3, eventType);
        set(4, invoiceId);
        set(5, paymentId);
        set(6, paymentStatus);
        set(7, paymentOperationFailureClass);
        set(8, paymentExternalFailure);
        set(9, paymentExternalFailureReason);
        set(10, paymentFee);
        set(11, paymentProviderFee);
        set(12, paymentExternalFee);
        set(13, paymentDomainRevision);
    }
}
