/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.magista.domain;


import com.rbkmoney.magista.domain.tables.Adjustment;
import com.rbkmoney.magista.domain.tables.InvoiceData;
import com.rbkmoney.magista.domain.tables.InvoiceEvent;
import com.rbkmoney.magista.domain.tables.PaymentData;
import com.rbkmoney.magista.domain.tables.PaymentEvent;
import com.rbkmoney.magista.domain.tables.PayoutEventStat;
import com.rbkmoney.magista.domain.tables.Refund;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>mst</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADJUSTMENT_PKEY = Indexes0.ADJUSTMENT_PKEY;
    public static final Index ADJUSTMENT_UKEY = Indexes0.ADJUSTMENT_UKEY;
    public static final Index INVOICE_DATA_INVOICE_CREATED_AT_IDX = Indexes0.INVOICE_DATA_INVOICE_CREATED_AT_IDX;
    public static final Index INVOICE_DATA_PKEY = Indexes0.INVOICE_DATA_PKEY;
    public static final Index INVOICE_DATA_UKEY = Indexes0.INVOICE_DATA_UKEY;
    public static final Index INVOICE_EVENT_INVOICE_ID_EVENT_CREATED_AT_IDX = Indexes0.INVOICE_EVENT_INVOICE_ID_EVENT_CREATED_AT_IDX;
    public static final Index INVOICE_EVENT_PKEY = Indexes0.INVOICE_EVENT_PKEY;
    public static final Index INVOICE_EVENT_UKEY = Indexes0.INVOICE_EVENT_UKEY;
    public static final Index PAYMENT_DATA_PAYMENT_CREATED_AT_IDX = Indexes0.PAYMENT_DATA_PAYMENT_CREATED_AT_IDX;
    public static final Index PAYMENT_DATA_PKEY = Indexes0.PAYMENT_DATA_PKEY;
    public static final Index PAYMENT_DATA_UKEY = Indexes0.PAYMENT_DATA_UKEY;
    public static final Index PAYMENT_EVENT_INVOICE_ID_PAYMENT_ID_EVENT_CREATED_AT_IDX = Indexes0.PAYMENT_EVENT_INVOICE_ID_PAYMENT_ID_EVENT_CREATED_AT_IDX;
    public static final Index PAYMENT_EVENT_PKEY = Indexes0.PAYMENT_EVENT_PKEY;
    public static final Index PAYMENT_EVENT_UKEY = Indexes0.PAYMENT_EVENT_UKEY;
    public static final Index PAYOUT_EVENT_PKEY = Indexes0.PAYOUT_EVENT_PKEY;
    public static final Index PAYOUT_EVENT_STAT_UKEY = Indexes0.PAYOUT_EVENT_STAT_UKEY;
    public static final Index REFUND_PKEY = Indexes0.REFUND_PKEY;
    public static final Index REFUND_UKEY = Indexes0.REFUND_UKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADJUSTMENT_PKEY = Internal.createIndex("adjustment_pkey", Adjustment.ADJUSTMENT, new OrderField[] { Adjustment.ADJUSTMENT.ID }, true);
        public static Index ADJUSTMENT_UKEY = Internal.createIndex("adjustment_ukey", Adjustment.ADJUSTMENT, new OrderField[] { Adjustment.ADJUSTMENT.EVENT_ID, Adjustment.ADJUSTMENT.EVENT_TYPE, Adjustment.ADJUSTMENT.ADJUSTMENT_STATUS }, true);
        public static Index INVOICE_DATA_INVOICE_CREATED_AT_IDX = Internal.createIndex("invoice_data_invoice_created_at_idx", InvoiceData.INVOICE_DATA, new OrderField[] { InvoiceData.INVOICE_DATA.INVOICE_CREATED_AT }, false);
        public static Index INVOICE_DATA_PKEY = Internal.createIndex("invoice_data_pkey", InvoiceData.INVOICE_DATA, new OrderField[] { InvoiceData.INVOICE_DATA.ID }, true);
        public static Index INVOICE_DATA_UKEY = Internal.createIndex("invoice_data_ukey", InvoiceData.INVOICE_DATA, new OrderField[] { InvoiceData.INVOICE_DATA.INVOICE_ID }, true);
        public static Index INVOICE_EVENT_INVOICE_ID_EVENT_CREATED_AT_IDX = Internal.createIndex("invoice_event_invoice_id_event_created_at_idx", InvoiceEvent.INVOICE_EVENT, new OrderField[] { InvoiceEvent.INVOICE_EVENT.INVOICE_ID, InvoiceEvent.INVOICE_EVENT.EVENT_CREATED_AT }, false);
        public static Index INVOICE_EVENT_PKEY = Internal.createIndex("invoice_event_pkey", InvoiceEvent.INVOICE_EVENT, new OrderField[] { InvoiceEvent.INVOICE_EVENT.ID }, true);
        public static Index INVOICE_EVENT_UKEY = Internal.createIndex("invoice_event_ukey", InvoiceEvent.INVOICE_EVENT, new OrderField[] { InvoiceEvent.INVOICE_EVENT.EVENT_ID, InvoiceEvent.INVOICE_EVENT.EVENT_TYPE, InvoiceEvent.INVOICE_EVENT.INVOICE_STATUS }, true);
        public static Index PAYMENT_DATA_PAYMENT_CREATED_AT_IDX = Internal.createIndex("payment_data_payment_created_at_idx", PaymentData.PAYMENT_DATA, new OrderField[] { PaymentData.PAYMENT_DATA.PAYMENT_CREATED_AT }, false);
        public static Index PAYMENT_DATA_PKEY = Internal.createIndex("payment_data_pkey", PaymentData.PAYMENT_DATA, new OrderField[] { PaymentData.PAYMENT_DATA.ID }, true);
        public static Index PAYMENT_DATA_UKEY = Internal.createIndex("payment_data_ukey", PaymentData.PAYMENT_DATA, new OrderField[] { PaymentData.PAYMENT_DATA.INVOICE_ID, PaymentData.PAYMENT_DATA.PAYMENT_ID }, true);
        public static Index PAYMENT_EVENT_INVOICE_ID_PAYMENT_ID_EVENT_CREATED_AT_IDX = Internal.createIndex("payment_event_invoice_id_payment_id_event_created_at_idx", PaymentEvent.PAYMENT_EVENT, new OrderField[] { PaymentEvent.PAYMENT_EVENT.INVOICE_ID, PaymentEvent.PAYMENT_EVENT.PAYMENT_ID, PaymentEvent.PAYMENT_EVENT.EVENT_CREATED_AT }, false);
        public static Index PAYMENT_EVENT_PKEY = Internal.createIndex("payment_event_pkey", PaymentEvent.PAYMENT_EVENT, new OrderField[] { PaymentEvent.PAYMENT_EVENT.ID }, true);
        public static Index PAYMENT_EVENT_UKEY = Internal.createIndex("payment_event_ukey", PaymentEvent.PAYMENT_EVENT, new OrderField[] { PaymentEvent.PAYMENT_EVENT.EVENT_ID, PaymentEvent.PAYMENT_EVENT.EVENT_TYPE, PaymentEvent.PAYMENT_EVENT.PAYMENT_STATUS }, true);
        public static Index PAYOUT_EVENT_PKEY = Internal.createIndex("payout_event_pkey", PayoutEventStat.PAYOUT_EVENT_STAT, new OrderField[] { PayoutEventStat.PAYOUT_EVENT_STAT.ID }, true);
        public static Index PAYOUT_EVENT_STAT_UKEY = Internal.createIndex("payout_event_stat_ukey", PayoutEventStat.PAYOUT_EVENT_STAT, new OrderField[] { PayoutEventStat.PAYOUT_EVENT_STAT.EVENT_ID, PayoutEventStat.PAYOUT_EVENT_STAT.EVENT_TYPE, PayoutEventStat.PAYOUT_EVENT_STAT.PAYOUT_STATUS }, true);
        public static Index REFUND_PKEY = Internal.createIndex("refund_pkey", Refund.REFUND, new OrderField[] { Refund.REFUND.ID }, true);
        public static Index REFUND_UKEY = Internal.createIndex("refund_ukey", Refund.REFUND, new OrderField[] { Refund.REFUND.EVENT_ID, Refund.REFUND.EVENT_TYPE, Refund.REFUND.REFUND_STATUS }, true);
    }
}
