/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.magista.domain;


import com.rbkmoney.magista.domain.tables.Adjustment;
import com.rbkmoney.magista.domain.tables.InvoiceData;
import com.rbkmoney.magista.domain.tables.InvoiceEvent;
import com.rbkmoney.magista.domain.tables.InvoiceEventStat;
import com.rbkmoney.magista.domain.tables.PaymentData;
import com.rbkmoney.magista.domain.tables.PaymentEvent;
import com.rbkmoney.magista.domain.tables.PayoutEventStat;
import com.rbkmoney.magista.domain.tables.Refund;
import com.rbkmoney.magista.domain.tables.records.AdjustmentRecord;
import com.rbkmoney.magista.domain.tables.records.InvoiceDataRecord;
import com.rbkmoney.magista.domain.tables.records.InvoiceEventRecord;
import com.rbkmoney.magista.domain.tables.records.InvoiceEventStatRecord;
import com.rbkmoney.magista.domain.tables.records.PaymentDataRecord;
import com.rbkmoney.magista.domain.tables.records.PaymentEventRecord;
import com.rbkmoney.magista.domain.tables.records.PayoutEventStatRecord;
import com.rbkmoney.magista.domain.tables.records.RefundRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>mst</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AdjustmentRecord, Long> IDENTITY_ADJUSTMENT = Identities0.IDENTITY_ADJUSTMENT;
    public static final Identity<InvoiceEventRecord, Long> IDENTITY_INVOICE_EVENT = Identities0.IDENTITY_INVOICE_EVENT;
    public static final Identity<InvoiceEventStatRecord, Long> IDENTITY_INVOICE_EVENT_STAT = Identities0.IDENTITY_INVOICE_EVENT_STAT;
    public static final Identity<PaymentEventRecord, Long> IDENTITY_PAYMENT_EVENT = Identities0.IDENTITY_PAYMENT_EVENT;
    public static final Identity<PayoutEventStatRecord, Long> IDENTITY_PAYOUT_EVENT_STAT = Identities0.IDENTITY_PAYOUT_EVENT_STAT;
    public static final Identity<RefundRecord, Long> IDENTITY_REFUND = Identities0.IDENTITY_REFUND;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdjustmentRecord> ADJUSTMENT_PKEY = UniqueKeys0.ADJUSTMENT_PKEY;
    public static final UniqueKey<InvoiceDataRecord> INVOICE_DATA_PKEY = UniqueKeys0.INVOICE_DATA_PKEY;
    public static final UniqueKey<InvoiceEventRecord> INVOICE_EVENT_PKEY = UniqueKeys0.INVOICE_EVENT_PKEY;
    public static final UniqueKey<InvoiceEventStatRecord> INVOICE_EVENT_STAT_PKEY = UniqueKeys0.INVOICE_EVENT_STAT_PKEY;
    public static final UniqueKey<PaymentDataRecord> PAYMENT_DATA_PKEY = UniqueKeys0.PAYMENT_DATA_PKEY;
    public static final UniqueKey<PaymentEventRecord> PAYMENT_EVENT_PKEY = UniqueKeys0.PAYMENT_EVENT_PKEY;
    public static final UniqueKey<PayoutEventStatRecord> PAYOUT_EVENT_PKEY = UniqueKeys0.PAYOUT_EVENT_PKEY;
    public static final UniqueKey<RefundRecord> REFUND_PKEY = UniqueKeys0.REFUND_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<InvoiceEventRecord, InvoiceDataRecord> INVOICE_EVENT__INVOICE_EVENT_INVOICE_ID_FKEY = ForeignKeys0.INVOICE_EVENT__INVOICE_EVENT_INVOICE_ID_FKEY;
    public static final ForeignKey<PaymentDataRecord, InvoiceDataRecord> PAYMENT_DATA__PAYMENT_DATA_INVOICE_ID_FKEY = ForeignKeys0.PAYMENT_DATA__PAYMENT_DATA_INVOICE_ID_FKEY;
    public static final ForeignKey<PaymentEventRecord, PaymentDataRecord> PAYMENT_EVENT__PAYMENT_EVENT_INVOICE_ID_FKEY = ForeignKeys0.PAYMENT_EVENT__PAYMENT_EVENT_INVOICE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AdjustmentRecord, Long> IDENTITY_ADJUSTMENT = createIdentity(Adjustment.ADJUSTMENT, Adjustment.ADJUSTMENT.ID);
        public static Identity<InvoiceEventRecord, Long> IDENTITY_INVOICE_EVENT = createIdentity(InvoiceEvent.INVOICE_EVENT, InvoiceEvent.INVOICE_EVENT.ID);
        public static Identity<InvoiceEventStatRecord, Long> IDENTITY_INVOICE_EVENT_STAT = createIdentity(InvoiceEventStat.INVOICE_EVENT_STAT, InvoiceEventStat.INVOICE_EVENT_STAT.ID);
        public static Identity<PaymentEventRecord, Long> IDENTITY_PAYMENT_EVENT = createIdentity(PaymentEvent.PAYMENT_EVENT, PaymentEvent.PAYMENT_EVENT.ID);
        public static Identity<PayoutEventStatRecord, Long> IDENTITY_PAYOUT_EVENT_STAT = createIdentity(PayoutEventStat.PAYOUT_EVENT_STAT, PayoutEventStat.PAYOUT_EVENT_STAT.ID);
        public static Identity<RefundRecord, Long> IDENTITY_REFUND = createIdentity(Refund.REFUND, Refund.REFUND.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AdjustmentRecord> ADJUSTMENT_PKEY = createUniqueKey(Adjustment.ADJUSTMENT, "adjustment_pkey", Adjustment.ADJUSTMENT.ID);
        public static final UniqueKey<InvoiceDataRecord> INVOICE_DATA_PKEY = createUniqueKey(InvoiceData.INVOICE_DATA, "invoice_data_pkey", InvoiceData.INVOICE_DATA.INVOICE_ID);
        public static final UniqueKey<InvoiceEventRecord> INVOICE_EVENT_PKEY = createUniqueKey(InvoiceEvent.INVOICE_EVENT, "invoice_event_pkey", InvoiceEvent.INVOICE_EVENT.ID);
        public static final UniqueKey<InvoiceEventStatRecord> INVOICE_EVENT_STAT_PKEY = createUniqueKey(InvoiceEventStat.INVOICE_EVENT_STAT, "invoice_event_stat_pkey", InvoiceEventStat.INVOICE_EVENT_STAT.ID);
        public static final UniqueKey<PaymentDataRecord> PAYMENT_DATA_PKEY = createUniqueKey(PaymentData.PAYMENT_DATA, "payment_data_pkey", PaymentData.PAYMENT_DATA.INVOICE_ID, PaymentData.PAYMENT_DATA.PAYMENT_ID);
        public static final UniqueKey<PaymentEventRecord> PAYMENT_EVENT_PKEY = createUniqueKey(PaymentEvent.PAYMENT_EVENT, "payment_event_pkey", PaymentEvent.PAYMENT_EVENT.ID);
        public static final UniqueKey<PayoutEventStatRecord> PAYOUT_EVENT_PKEY = createUniqueKey(PayoutEventStat.PAYOUT_EVENT_STAT, "payout_event_pkey", PayoutEventStat.PAYOUT_EVENT_STAT.ID);
        public static final UniqueKey<RefundRecord> REFUND_PKEY = createUniqueKey(Refund.REFUND, "refund_pkey", Refund.REFUND.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<InvoiceEventRecord, InvoiceDataRecord> INVOICE_EVENT__INVOICE_EVENT_INVOICE_ID_FKEY = createForeignKey(com.rbkmoney.magista.domain.Keys.INVOICE_DATA_PKEY, InvoiceEvent.INVOICE_EVENT, "invoice_event__invoice_event_invoice_id_fkey", InvoiceEvent.INVOICE_EVENT.INVOICE_ID);
        public static final ForeignKey<PaymentDataRecord, InvoiceDataRecord> PAYMENT_DATA__PAYMENT_DATA_INVOICE_ID_FKEY = createForeignKey(com.rbkmoney.magista.domain.Keys.INVOICE_DATA_PKEY, PaymentData.PAYMENT_DATA, "payment_data__payment_data_invoice_id_fkey", PaymentData.PAYMENT_DATA.INVOICE_ID);
        public static final ForeignKey<PaymentEventRecord, PaymentDataRecord> PAYMENT_EVENT__PAYMENT_EVENT_INVOICE_ID_FKEY = createForeignKey(com.rbkmoney.magista.domain.Keys.PAYMENT_DATA_PKEY, PaymentEvent.PAYMENT_EVENT, "payment_event__payment_event_invoice_id_fkey", PaymentEvent.PAYMENT_EVENT.INVOICE_ID, PaymentEvent.PAYMENT_EVENT.PAYMENT_ID);
    }
}
